### ISSUE TITLE
Tests fail with ActiveSupport 4.0.0+

### ISSUE THREAD

**Issue by ChrisLundquist** [jnunemaker/flipper#29]
Failures look like:
```
Failures:

  1) Flipper::Instrumentation::LogSubscriber feature enabled checks logs feature calls with result after operation
     Failure/Error: raise("Could not find line matching #{str.inspect} in #{lines.inspect}")
     RuntimeError:
       Could not find line matching "Flipper feature(search) enabled? false" in []
     # ./spec/flipper/instrumentation/log_subscriber_spec.rb:105:in `find_line'
     # ./spec/flipper/instrumentation/log_subscriber_spec.rb:35:in `block (3 levels) in <top (required)>'
```

Works fine with `< 4.0.0`
