### ISSUE TITLE
Ruby 1.8.x support

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#9]
Currently the Actor#id stuff fails on 1.8. 

```
Failures:

  1) Flipper::DSL#actor for a number returns actor instance with identifer set to number
     Failure/Error: actor.identifier.should eq(33)

       expected: 33
            got: 67

       (compared using ==)
     # ./spec/flipper/dsl_spec.rb:151

  2) Flipper::Types::Actor converts identifier to integer
     Failure/Error: actor.identifier.should eq(2)

       expected: 2
            got: 2156693720

       (compared using ==)
     # ./spec/flipper/types/actor_spec.rb:90

  3) Flipper::Types::Actor has identifier
     Failure/Error: actor.identifier.should eq(2)

       expected: 2
            got: 5

       (compared using ==)
     # ./spec/flipper/types/actor_spec.rb:95

  4) Flipper::Types::Actor.wrappable? returns false if not actor and does not respond to identifier, id, nor to_i
     Failure/Error: described_class.wrappable?(:nope).should be_false
       expected: false value
            got: true
     # ./spec/flipper/types/actor_spec.rb:44
```

I'm thinking I'll just drop support for #id and force using identifier or something like that more specific to flipper.
